"""Questions and answers """
question_data = [
    {
        "category": "Mythology",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Norse mythology, Thor once dressed as a woman.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "medium",
        "question": "There aren&#039;t any live-action clones in &quot;Star Wars: Episode III - Revenge of the Sith&quot;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Comics",
        "type": "boolean",
        "difficulty": "hard",
        "question": "In the comic book &quot;Archie&quot;, Betty is friends with Veronica because she is rich.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are no deserts in Europe.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A flock of crows is known as a homicide.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Valve&#039;s &quot;Portal&quot; and &quot;Half-Life&quot; franchises exist within the same in-game universe.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Hidden in the files for &quot;Mario Kart Arcade GP&quot; is a picture of the Beslan school hostage crisis.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
